---
title: "Abgabe Datenanalyse"
author: "Sandro Kostenzer"
output: html_document
date: "2024-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data <- read.csv('./Data/MBA.csv')
library(knitr)
library("GGally")
library("ggplot2")
library(dplyr)
```

## Datenanalyse
```{r analyse}
median(data$gmat)
cor(data$gmat, data$gpa)

kable(quantile(data$gmat), caption = "Quantile mit knitr")
```

## Univariate Grafiken
```{r univariat}
ggplot(data, aes(x=gmat))+
  geom_histogram(color='black', fill='lightblue', binwidth = 10,boundary = 560)+
  scale_x_continuous(breaks = seq(540,800, by = 20))+
  theme_minimal() +
  labs(title = "GMAT Score of Applicants of Warthon Class", y='Count', x='GMAT Score')


races <- data$race[!is.na(data$race) & data$race != ""]
race_counts <- table(races) %>%
  as.data.frame() %>%
  rename(Race = races, Count = Freq) %>%
  mutate(Percentage = Count / sum(Count) * 100)

ggplot(race_counts, aes(x = "", y = Count, fill = Race)) +
  geom_bar(stat = "identity", width = 1)+
  geom_text(aes(label = paste0(round(Percentage, 1), "%")),
            position = position_stack(vjust = 0.5), size = 4) +
  coord_polar(theta = "y") +
  theme_minimal()+
  theme(axis.text.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid = element_blank()) +
  labs(title = "Distribution of Races", fill = "Race", x="", y ="") +
  scale_fill_brewer(palette = "Set2")
```

## Bivariate Grafiken
```{r bivariat}
boxplot(data$gmat~data$major,
        ylab="GMAT score",
        xlab="Undergraduate Major")

ggplot(data, aes(x = gmat, fill = gender)) +
  geom_histogram(bins = 30, position = "identity", color = "white", alpha = 0.7) +
  facet_grid(gender ~ .) +
  coord_flip() +
  theme_minimal() +
  labs(x = "GMAT Score", y = "Count", title = "Distribution of GMAT Scores by Gender")

```